# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Position(object):
    def setupUi(self, Position):
        Position.setObjectName("Position")
        Position.resize(520, 220)
        Position.setMinimumSize(QtCore.QSize(520, 220))
        Position.setMaximumSize(QtCore.QSize(520, 220))
        self.position = QtWidgets.QLabel(Position)
        self.position.setGeometry(QtCore.QRect(0, 0, 521, 221))
        self.position.setText("")
        self.position.setPixmap(QtGui.QPixmap("graphic/position.png"))
        self.position.setScaledContents(True)
        self.position.setObjectName("position")

        self.retranslateUi(Position)
        QtCore.QMetaObject.connectSlotsByName(Position)

    def retranslateUi(self, Position):
        _translate = QtCore.QCoreApplication.translate
        Position.setWindowTitle(_translate("Position", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Position = QtWidgets.QDialog()
    ui = Ui_Position()
    ui.setupUi(Position)
    Position.show()
    sys.exit(app.exec_())
