# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Wall(object):
    def setupUi(self, wall):
        wall.setObjectName("Dialog")
        wall.resize(640, 216)
        wall.setMinimumSize(QtCore.QSize(640, 220))
        wall.setMaximumSize(QtCore.QSize(640, 220))
        self.label = QtWidgets.QLabel(wall)
        self.label.setGeometry(QtCore.QRect(0, 0, 640, 220))
        self.label.setMinimumSize(QtCore.QSize(640, 220))
        self.label.setMaximumSize(QtCore.QSize(459, 220))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("graphic/wall.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(wall)
        QtCore.QMetaObject.connectSlotsByName(wall)

    def retranslateUi(self, wall):
        _translate = QtCore.QCoreApplication.translate
        wall.setWindowTitle(_translate("wall", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wall = QtWidgets.QDialog()
    ui = Ui_Wall()
    ui.setupUi(wall)
    wall.show()
    sys.exit(app.exec_())
