# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_width(object):
    def setupUi(self, width):
        width.setObjectName("width")
        width.resize(650, 380)
        width.setMinimumSize(QtCore.QSize(650, 380))
        width.setMaximumSize(QtCore.QSize(650, 380))
        self.label = QtWidgets.QLabel(width)
        self.label.setGeometry(QtCore.QRect(0, 0, 651, 381))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("graphic/width.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(width)
        QtCore.QMetaObject.connectSlotsByName(width)

    def retranslateUi(self, width):
        _translate = QtCore.QCoreApplication.translate
        width.setWindowTitle(_translate("width", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    width = QtWidgets.QDialog()
    ui = Ui_width()
    ui.setupUi(width)
    width.show()
    sys.exit(app.exec_())
